<html>
    <p>2016112220 양소영</p>
    <body>
        <p>Please input a number between 5 and 10:</p>
        <input id="demo" type="text">
        <button type="button" onclick="myFunction()">Test Input</button>
        <p id="message"></p>

        <script>
            function myFunction() {
                var message, x;
                message = document.getElementById("message"); // id의 값이 message인 요소의 내용을 변수 message에 저장한다.
                message.innerHTML = ""; // 변수 message의 내용을 가져와 ""로 바꾼다.
                x = document.getElementById("demo").value; // id의 값이 demo인 요소의 값을 변수 x에 저장한다.
                /* document.getElementById("message").innerHTML = x  
                * 5~10 사이 입력한 값 출력하는 코드 
                * id의 값이 message인 요소 내용을 변수 x에 저장된 값으로 바꾼다. */
                try{
                    if(x == "") throw " is empty";
                    if(isNaN(x)) throw " is not a number";
                    x = Number(x); // Number()은 문자열을 숫자로 변환하는 함수이다.
                    if(x>10) throw " is too high";
                    if(x<5) throw " is too low";
                } 
                catch(err) {
                    message.innerHTML = "Input" + err;
                }
                finally{ 
                    document.getElementById("demo").value = "";
                }
            }
        </script>
    </body>
</html>
<!-- Number( object )
    - object : 문자열 또는 문자열을 값으로 하는 변수 등을 입력한다.
    - 숫자로 변환할 수 없는 값인 경우 NaN을 반환한다. -->
<!-- try..catch..finally
    1. try 블록: 실행될 선언들
    2. catch 블록
        - try 블록 안에서 예외가 발생(throw)하는 경우 무엇을 할지 명시하는 코드를 포함함.
        - try 블록 (또는 try 블록 내에서 호출된 함수) 내의 명령문이 예외를 throw 하면 제어가 catch 블록으로 이동함. 
        - try 블록에 예외가 발생하지 않으면 catch 블록을 건너뜀.
    3. finally 블록: try 선언이 완료된 이후에 실행된 선언들. 이 선언들은 예외 발생 여부와 상관없이 실행됨. -->